# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'xfrubiks' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xfrubiks
  #pod 'ReactiveCocoa', '~> 4.1'
  #pod 'PromiseKit', '~> 3.2'
  pod 'Masonry', '~> 1.0'
  pod 'TWMessageBarManager', '~> 1.8'
  pod 'SVProgressHUD', '~> 2.0'

end
